In [354]:
import numpy as np

print(np.__version__)

2.3.1


Array initialization from already existing Python list

In [355]:
import numpy as np
temp = [1,2,3,4,5]
temp_numpy = np.array(temp)
temp_numpy = np.array(temp)
print(temp_numpy)
print(temp_numpy.shape, temp_numpy.dtype, temp_numpy.size, temp_numpy.ndim)


[1 2 3 4 5]
(5,) int64 5 1


0-zero() and 1-ones() array

In [356]:
import numpy as np

zeros = np.zeros(5)
ones = np.ones(10)

zeros_2d = np.zeros((2,4))
ones_2d = np.ones((3,5))
print(zeros, ones)
print(zeros_2d, ones_2d)

[0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]] [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Full numpy array with a chosen number

In [357]:
import numpy as np

full_array = np.full((3,5), -69)

print(full_array)

[[-69 -69 -69 -69 -69]
 [-69 -69 -69 -69 -69]
 [-69 -69 -69 -69 -69]]


arange() -> it's basically range() in python i guess

In [358]:
import numpy as np

new = np.arange(0, 10)
new_even = np.arange(0, 10, 2)

print(new)
print(new_even)


[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


Identity matrix

In [359]:
import numpy as np

identity = np.eye(10)

print(identity)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


RANDOM ARRAY

In [360]:
import numpy as np
#The seed can be anything i guess -> seed determines the random values
np.random.seed(69420)

bogo_array = np.random.rand(4,3) #random from 0-1
int_bogo_array = np.random.randint(-69, 69, (5,5)) #from lower - upper

print(bogo_array)
print(int_bogo_array)


[[0.53109224 0.35676397 0.51311614]
 [0.32530468 0.45724967 0.01407327]
 [0.45984102 0.35495298 0.98303443]
 [0.42366256 0.60327198 0.32626615]]
[[ 22  68  45  61   9]
 [-29 -25   1 -37 -36]
 [-51  36  21 -59  -5]
 [-60 -37  58  21   6]
 [-32 -13  66  32  48]]


Accessing arrays

1. Indexing

In [361]:
import numpy as np

new = np.array([1,2,3,4,5])

first_element = new[0]

last_element = new[-1]

print(first_element, last_element)

1 5


In [362]:
import numpy as np

arr_2d = np.array([[2,3,4],[5,6,7]])

print(arr_2d[0, 2])

4


2. Slicing

ex01: From a 1d array, we take out the subarray from the 2nd element to the 4th element

In [363]:
import numpy as np

nums = np.array([1,2,3,4,5])

print(nums[1:4])

[2 3 4]


ex02: From a 2d array, we take out the data from row 2 and 3

In [364]:
import numpy as np

nums = np.array([[1,2], [3,4], [5,6]])

print(nums)
print(nums[1:3])

[[1 2]
 [3 4]
 [5 6]]
[[3 4]
 [5 6]]


ex03: From a 2d array, we take out the last 2 rows of them, and the last 2 columns as well

In [365]:
import numpy as np

nums = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(nums)

print(nums[-2:,-2:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]


Connect arrays
1. hstack

In [366]:
#hstack connects the arrays horizontally

import numpy as np

arr_1 = np.array([1,2,3,4,5])

arr_2 = np.array([-1,-2,-3,-4,-5])

print(np.hstack((arr_1, arr_2)))

[ 1  2  3  4  5 -1 -2 -3 -4 -5]


vstack

In [367]:
#i mean hstack is for horizontal connection, probably can guess what vstack does huh

import numpy as np

arr_1 = np.array([1,2,3,4,5])

arr_2 = np.array([-1,-2,-3,-4,-5])

print(np.vstack((arr_1, arr_2)))

[[ 1  2  3  4  5]
 [-1 -2 -3 -4 -5]]


concatenate

In [368]:
'''
basically hstack + vstack, connect arrays and can choose any direction we want
axis = 0 -> vertical
axis = 1 -> horizontal

NOTE: cant use this to connect 1d array horizontally -> use the hstack boy instead
'''

import numpy as np


arr_1 = np.array([[1,2,3,4],[5,6,7,8]])

arr_2 = np.array([[-1,-2,-3,-4],[-5,-6,-7,-8]])

hstack_imposter = np.concatenate((arr_1, arr_2), axis = 1)
vstack_imposter = np.concatenate((arr_1, arr_2), axis = 0)

print(hstack_imposter)
print(vstack_imposter)




[[ 1  2  3  4 -1 -2 -3 -4]
 [ 5  6  7  8 -5 -6 -7 -8]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [-1 -2 -3 -4]
 [-5 -6 -7 -8]]


Change shape and dim of arrays
1. slicing, expand_dims

In [369]:
'''
np.newaxis -> adds one more dimension inside (sus)
I think u can use None instead of that sooo,
maybe None is goated
'''

import numpy as np

arr = np.array([1,2,3,4,5])
print(arr, arr.shape)
#1D -> 2D (1 row of 5 elements)
arr_2d = arr[np.newaxis, :]
print(arr_2d, arr_2d.shape)

#1D -> 2D (5 rows of 1 element)
arr_2d = arr[:, np.newaxis]
print(arr_2d, arr_2d.shape)




[1 2 3 4 5] (5,)
[[1 2 3 4 5]] (1, 5)
[[1]
 [2]
 [3]
 [4]
 [5]] (5, 1)


In [370]:
'''
np.expand_dims(): Basically a function that adds another 
axis to it, not rly sure what is the difference tho

I think it is more clear to see which axis it expands on,
so that's nice

'''
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)
print()
#2d -> 3d


for i in range(0, 3):
    arr_3d = np.expand_dims(arr, axis = i)
    print(arr_3d, arr_3d.shape)
    print()


[[1 2 3]
 [4 5 6]] (2, 3)

[[[1 2 3]
  [4 5 6]]] (1, 2, 3)

[[[1 2 3]]

 [[4 5 6]]] (2, 1, 3)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]] (2, 3, 1)



2. reshape (oh shit this is gonna be confusing)


In [371]:
""" 
Basically it reshapes it. Surprise huh

as long as the area/ volumes or whatever it is in higher dimension is
the same between the old and new shape, it can basically do a transform
from tinybot to fucking gigachad

NOTE:
oh and this as well.

suppose u have a (69, 420) array (probably never)
u want it now to have 3x less rows, and therefore, 3x more columns

u do some quick mental math like the asian you are and get 23 rows for
the new shape, but your attention span is low and can't really piece 
together wtf 420 * 3 is

soooooo, yeah numpy now does it for you using the -1 magic number
...
EZ

"""

import numpy as np
arr_2d = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

#Compressing to 1d

new = np.reshape(arr_2d, shape = (-1, ))
print(new)

#to 3 * 4
new = np.reshape(arr_2d, shape = (3, 4))
print(new)

#to 6 rows and sth(let numpy calc it)
new = np.reshape(arr_2d, shape = (6, -1))
print(new)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


Searching and sorting
1. With conditions

In [372]:
'''
np.where(): It does what it sounds like

1 condition, bam bam bam -> returns the INDEXES that sastify it

'''

import numpy as np

arr = np.array([i - 50 for i in range(0, 100)]) #list compression type sh

result = np.where(arr % 2 == 1)

print(result)
print(arr[result])

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]),)
[-49 -47 -45 -43 -41 -39 -37 -35 -33 -31 -29 -27 -25 -23 -21 -19 -17 -15
 -13 -11  -9  -7  -5  -3  -1   1   3   5   7   9  11  13  15  17  19  21
  23  25  27  29  31  33  35  37  39  41  43  45  47  49]


Max and Min

In [373]:
''' 
probably no need to explain this huh
'''

import numpy as np
arr = np.array([1,2,3,4,5])

max_value, min_value = np.max(arr), np.min(arr)

print(max_value, min_value)


5 1


In [374]:
''' 
But wait there's more

It can actually do it with each axis in a multiple dimension array
'''

import numpy as np

arr = np.array([[1,2,3,4,5], [-1,-2,-3,-4,-5]])

max_value_row, min_value_row = np.max(arr, axis = 1), np.min(arr, axis = 1)

print(max_value_row, min_value_row)

[ 5 -1] [ 1 -5]


Find the indexes of the max and min

In [375]:
''' 
still, pretty simple
we use argmax and argmin, along some axis
-> so basically groups/ compresses them along some axis, 
like group by in sql -> do the mental math -> return indexes

axis = cool
'''
import numpy as np

arr = np.array([[10, 15, 12], [13, 14, 9]])

index_max, index_min = np.argmax(arr), np.argmin(arr)

print(index_max, index_min)

print(np.argmax(arr, axis = 0))
print(np.argmin(arr, axis = 1))


1 5
[1 0 0]
[0 2]


sorting 

In [376]:
''' 
also pretty simple, kinda boring actually

np.sort()
 but nows includes an axis as well, so it sorts within each subarray 
 axis direction i guess
'''

import numpy as np


arr = np.array([[3,1,-2],[6,-5,4]])

#default
print(np.sort(arr))

#row by row
print(np.sort(arr, axis = 1))

#column by column
print(np.sort(arr, axis = 0))




[[-2  1  3]
 [-5  4  6]]
[[-2  1  3]
 [-5  4  6]]
[[ 3 -5 -2]
 [ 6  1  4]]


MATH TIME WOOHOO

In [377]:
''' 
Addition: 
    so
    basically
     c = a + b
    and in terms of numpy, it basically add each element together
    like vector/ matrix addition

    and they need to be the same shape, obviously

    '+' and np.add() are the same
'''

import numpy as np

arr1 = np.array([-3, -5, -9, 2])

arr2 = np.array([1, 2, 3, 4])

print(arr1 + arr2)
print(np.add(arr1, arr2))

[-2 -3 -6  6]
[-2 -3 -6  6]


In [378]:
''' 
subtraction: basically addition in reverse, not much to say

-> '-' = np.substract()


'''

import numpy as np

arr1 = np.array([-3, -5, -9, 2])

arr2 = np.array([1, 2, 3, 4])

print(arr1 - arr2)
print(np.subtract(arr1, arr2))


[ -4  -7 -12  -2]
[ -4  -7 -12  -2]


In [379]:
''' 
multiplication: the same applys here

'*' = np.multiply()
'''

import numpy as np

arr1 = np.array([-3, -5, -9, 2])

arr2 = np.array([1, 2, 3, 4])

print(arr1 * arr2)
print(np.multiply(arr1, arr2))

[ -3 -10 -27   8]
[ -3 -10 -27   8]


In [380]:
''' 
division is zzzzzzzzzzzzzzzzzzzzzz

'/' = np.divide()

// works which is surprising

'''


import numpy as np

arr1 = np.array([-3, -5, -9, 2])

arr2 = np.array([1, 2, 3, 4])

print(arr1 / arr2)
print(np.divide(arr1, arr2))

print(arr1 // arr2)

[-3.  -2.5 -3.   0.5]
[-3.  -2.5 -3.   0.5]
[-3 -3 -3  0]


In [381]:
''' 
    Now the fun stuff begins.

    dot product

    a = [a1, a2, a3, ..., an], b = [b1, b2, b3, ..., bn]

    -> np.dot(a.b) (or math-wise a.b) = a1 * a2 + b1 * b2 + ... to the end

    NOTE:
    in math wise: it should be the same shape
    but numpy wise: 

    if one arr has shape (1, 2), it can actually do a dot product
    with a shape that is (2, 1)
    so that is neet
'''

import numpy as np

#same shape
arr_1 = np.array([1,2])
arr_2 = np.array([2,3])
print(arr_1.dot(arr_2))

#shape a bit diff
arr_1 = np.array([1,2])
arr_2 = np.array([[2],[3]])

print(arr_1.dot(arr_2))



8
[8]


In [382]:
''' 
matrix- matrix multiplication (np.matmul() i think np.dot() also works
but kinda sketchy)

a11  a12   b11  b12     c11 c12
         *           =
a21  a22   b21  b22     c21 c22

and c11 = a11 * b11 + a12 * b21 (basically dot product of 1st row of a
                                and 1 col of b)

    the rule applies

    c[i][j] = dot product of i-th row of a and j-th col of b

NOTE:

for this to happen
a needs to have a shape of (m, n) -> b needs to have a shape of(n,k)
a has n cols, b has n rows -> final shape will be m x k
'''

import numpy as np

arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[-1], [-2], [-3]])
print(arr1)
print(arr2)
print()
print(np.matmul(arr1, arr2))
print(arr1)


[[1 2 3]
 [4 5 6]]
[[-1]
 [-2]
 [-3]]

[[-14]
 [-32]]
[[1 2 3]
 [4 5 6]]


In [383]:
''' 
Transposition

(A)T is the transpose of matrix A

if A has shape(a,b) -> the transpose has shape (b,a)

for every i,j  (A)T [i][j] = A[j][i]

use np.transpose()
'''

import numpy as np

arr1 = np.array([[1,2],[3,4],[5,6]])
arr2 = np.transpose(arr1)
print(arr1)
print(arr2)


[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


SOME EXERCISES/EZ FUNCTIONS FOR NOOBS

In [384]:
''' 
    Find the average of a numpy array

    np.mean()

'''

arr_1 = np.array([1,2,3,4,5])
print(np.mean(arr_1))


3.0


In [385]:
''' 
    Find the length of a vector

    np.linalg.norm()
'''

vector = np.array([1,2,3])

print(round(np.linalg.norm(vector), 2))

3.74


In [386]:
'''
    solve a system a linear equation
    Ax = B
    np.linalg.solve()
'''

a = np.array([[3,1], [1,2]])
b = np.array([9, 8])

print(np.linalg.solve(a,b))

[2. 3.]


BROADCASTING (huh wtf isthis)

In [387]:
''' 
so i think it basically let us 
do math with diffent shape and sizes

numpy expands the smaller size array (if possible)
so that both has the same size
and he does the asian math thingy afterwards
'''

#extend 2 -> [2 2 2 2]
import numpy as np

arr = np.array([1,3,5,7])

print(arr * 2)


[ 2  6 10 14]


In [388]:
#2d shit for illustration

arr2d = np.array([[1,3,4], [7,8,0]])

arr1d = np.array([-1,-2,-3])

print(arr2d + arr1d)

# the same is :
# arr1d = np.array([[-1,-2,-3], [-1,-2,-3]])
# print(arr2d + arr1d)

[[ 0  1  1]
 [ 6  6 -3]]


In [389]:
#another 2d shit
import numpy as np
 
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([10, 20, 30])

print(arr1 * arr2)

#basically the same ap np.matmul()


[[10 20 30]
 [20 40 60]
 [30 60 90]]


FUCNTIONS AND SHI

In [ ]:
''' 
np.apply_along_axis(func, axis, arr)

this is basically a struct func use in cpp i think
basically a packaged function u can made yourself,
and apply it along the axis

'''

import numpy as np

def avg(arr):
    return round(np.mean(arr), 3)

arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

#avg of each column
print(np.apply_along_axis(avg, axis = 0, arr=arr2d))

#avg of each row
print(np.apply_along_axis(avg, axis = 1, arr=arr2d))


[4. 5. 6.]
[2. 5. 8.]


In [ ]:
'''
vectorize:
isn't this basically a for loop?
even the official documentation said that:
"The vectorize function is provided primarily 
for convenience, not for performance. The implementation
 is essentially a for loop.

 bro wtf is it rly necessary

 it basically applys any function u have to apply 
 along each element of a vector
'''

def celcius_to_fahreinheit(c):
    return (c * 9 / 5) + 32

vectorize_function = np.vectorize(celcius_to_fahreinheit)

celcius = np.array([-1, 20.5, 97.5, 100, 56.5])

print(vectorize_function(celcius))
